spring:
    datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mysql://ec2-52-3-111-21.compute-1.amazonaws.com:33306/spring_db?useUnicode=true&charaterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      hikari: #hikari 설정 정보
        username: root
        password: password

    jpa:
        database-platform: org.hibernate.dialect.MariaDB53Dialect
        hibernate:
            ddl-auto: update
            
    security:
      oauth2:
        client:
          registration:
            google:
              clientId: 
              clientSecret: 
              redirectUriTemplate: "{baseUrl}/oauth2/callback/{registrationId}"
              scope:
                - email
                - profile
            facebook:
              clientId: 
              clientSecret: 
              redirectUriTemplate: "{baseUrl}/oauth2/callback/{registrationId}"
              scope:
                - email
                - public_profile
            github:
              clientId: 
              clientSecret: 
              redirectUriTemplate: "{baseUrl}/oauth2/callback/{registrationId}"
              scope:
                - user:email
                - read:user
            kakao:
              clientId: 
              clientSecret: 
              redirectUriTemplate: "{baseUrl}/oauth2/callback/{registrationId}"
              scope:
                - profile
            naver:
              clientId: 
              clientSecret: 
              redirectUriTemplate: "{baseUrl}/oauth2/callback/{registrationId}"
              scope:
                - public_profile
                - email
#          provider:
#            facebook:
#              authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
#              tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
#              userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)
app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 864000000
  oauth2:
    # After successfully authenticating with the OAuth2 Provider,
    # we'll be generating an auth token for the user and sending the token to the
    # redirectUri mentioned by the client in the /oauth2/authorize request.
    # We're not using cookies because they won't work well in mobile clients.
    authorizedRedirectUris:
      - http://localhost:3000/oauth/redirect
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect
      - http://ed51579b-default-springser-29a1-1434439925.us-east-1.elb.amazonaws.com/oauth/redirect
      - http://studyon.shop/oauth/redirect